# Dependencies
markdown:            redcarpet
highlighter:         pygments
gems: [jekyll-paginate, jekyll-gist]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# permalink:          /:categories/:title/
#relative_permalinks: true

# Setup
title:               pixelwright
tagline:             'UI Development & Design'
description:         '<strong>pixel</strong> <em>noun</em> <strong>1</strong> A minute area of illumination on a display screen.<br><strong>wright</strong> <em>noun</em> (obsolete) <strong>1</strong> A builder or creator of something.'
url:                 http://pixel.wright.is
baseurl:             /
blogurl:             /
bloghome:            /index.html
projectsurl:         /projects/
projectshome:        /projects/index.html
paginate:            5
paginate_path:       "/page:num"

# About/contact
author:
  name:              Will Wright
  twitter:           https://twitter.com/WilliamWright
  email:             will@wright.is
github:
  repo:              https://github.com/willwright82/willwright82.github.io

# Custom vars
version:             3.0.1
