# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com

author:
  name:           'Will Wright'
  url:            https://twitter.com/WilliamWright

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://pixel.wright.is/new/